setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:/lab/limatb/app/MUMPS/MUMPS_5.0.0_FILES_fPIC_OpenBLAS/lib
setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:/lab/limatb/app/MUMPS/OpenBLAS/Install/lib
setenv ELMER /lab/limatb/app/ELMER/VERSIONs/ELMERDEB7MUMPSV5OpenBLAS
setenv PATH $ELMER/bin:${PATH}
setenv OPENBLAS_NUM_THREADS 16

